import { NextRequest, NextResponse } from 'next/server'; import { z } from 'zod'; import { createHmac, timingSafeEqual } from 'node:crypto'; import { db } from '@/lib/db'; import { jsonError } from '@/lib/http'; import { salesforceProvider } from '@/integrations/salesforce/provider';
const schema = z.object({ eventId: z.string().min(1), item: z.object({ externalId: z.string().min(1), restaurantExternalId: z.string().min(1), name: z.string().min(1), description: z.string().optional(), imageUrl: z.string().optional(), categoryName: z.string().optional(), foodType: z.enum(['VEG','NON_VEG','EGG','VEGAN']), price: z.number().nonnegative(), quantity: z.number().nonnegative().optional(), unit: z.string().optional(), servingSize: z.string().optional(), spiceLevel: z.string().optional(), preparationMins: z.number().int().nonnegative().optional(), ingredients: z.array(z.string()).optional(), allergens: z.array(z.string()).optional(), available: z.boolean().optional() }) });
function authorized(req: NextRequest, raw: string) { const secret = process.env.SALESFORCE_WEBHOOK_SECRET; if (!secret) return process.env.NODE_ENV !== 'production'; const got = (req.headers.get('x-scanzaa-signature') || '').replace(/^sha256=/, ''); const expected = createHmac('sha256', secret).update(raw).digest('hex'); const a = Buffer.from(got); const b = Buffer.from(expected); return a.length === b.length && timingSafeEqual(a,b); }
export async function POST(req: NextRequest) { try {
 const raw = await req.text(); if (!authorized(req, raw)) return NextResponse.json({ error: 'Invalid integration signature' }, { status: 401 }); const input = schema.parse(JSON.parse(raw)); const prior = await db.integrationEvent.findUnique({ where: { eventId: input.eventId } }); if (prior?.status === 'SUCCEEDED') return NextResponse.json({ duplicate: true });
 await db.integrationEvent.upsert({ where: { eventId: input.eventId }, create: { provider: 'salesforce', eventId: input.eventId, eventType: 'menu.upsert', payload: input, status: 'PROCESSING', attempts: 1 }, update: { status: 'PROCESSING', attempts: { increment: 1 }, error: null } });
 try { const { item } = input; const restaurant = await db.restaurant.findUnique({ where: { externalId: item.restaurantExternalId } }); if (!restaurant) throw new Error('Unknown restaurantExternalId'); await salesforceProvider.syncMenu(item);
  const category = item.categoryName ? await db.menuCategory.upsert({ where: { restaurantId_name: { restaurantId: restaurant.id, name: item.categoryName } }, create: { restaurantId: restaurant.id, name: item.categoryName }, update: {} }) : null;
  const data = { name: item.name, description: item.description || '', imageUrl: item.imageUrl || '', categoryId: category?.id, foodType: item.foodType, price: item.price, quantity: item.quantity ?? 1, unit: item.unit || 'portion', servingSize: item.servingSize || 'Serves 1', spiceLevel: item.spiceLevel, preparationMins: item.preparationMins, ingredients: item.ingredients || [], allergens: item.allergens || [], available: item.available ?? true };
  const existing = await db.menuItem.findUnique({ where: { externalId: item.externalId } }); const result = await db.menuItem.upsert({ where: { externalId: item.externalId }, create: { ...data, restaurantId: restaurant.id, externalId: item.externalId }, update: data });
  await db.integrationEvent.update({ where: { eventId: input.eventId }, data: { status: 'SUCCEEDED', processedAt: new Date() } }); return NextResponse.json({ result: existing ? 'updated' : 'created', menuItem: result });
 } catch(error) { await db.integrationEvent.update({ where: { eventId: input.eventId }, data: { status: 'FAILED', error: error instanceof Error ? error.message : 'Processing failed' } }); throw error; }
 } catch(e) { return jsonError(e); } }
