'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Camera, Check, ChevronDown, ImagePlus, Upload, UtensilsCrossed } from 'lucide-react';
import './menu-management.css';

type Dish = { id?: string; name: string; category: string; type: 'Veg'|'Non-Veg'|'Egg'|'Vegan'; price: number; qty: number; unit: string; serving: string; available: boolean; image: string; description: string; time: string; spice: string; ingredients?: string[]; allergens?: string[] }|null;
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="dish-field"><span>{label}</span>{children}</label>; }

export function DishEditor({ form, update, close, save, notice, item, restaurantId }: { form: Record<string,string>; update: (key:string,value:string)=>void; close:()=>void; save:()=>void; notice:(message:string)=>void; item:Dish; restaurantId:string }) {
  const [categories,setCategories]=useState<string[]>([]);
  const [nutritionOpen,setNutritionOpen]=useState(false);
  const [image,setImage]=useState(form.image||'');
  useEffect(()=>{if(!restaurantId)return;fetch(`/api/restaurants/${restaurantId}/categories`).then(response=>response.ok?response.json():null).then(result=>{if(result?.data)setCategories(result.data.map((category:{name:string})=>category.name))}).catch(()=>{})},[restaurantId]);
  const selectedImage=image||item?.image||'';
  const previewPrice=useMemo(()=>form.pricingMode==='PORTIONS'?form.priceQuarter||form.priceHalf||form.priceFull||form.price:form.pricingMode==='DRY_GRAVY'?form.priceDry||form.priceGravy||form.price:form.price,[form]);
  const readImage=(file?:File)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){notice('Use a JPG, PNG, or WebP image');return}if(file.size>5*1024*1024){notice('Image must be 5 MB or smaller');return}const reader=new FileReader();reader.onload=()=>{const value=String(reader.result);setImage(value);update('image',value)};reader.readAsDataURL(file)};
  const priceField=(key:string,label:string)=> <Field key={key} label={label}><div className="dish-input-prefix"><span>₹</span><input type="number" min="0" value={form[key]||''} placeholder="0" onChange={event=>{update(key,event.target.value);if(!form.price||key==='priceQuarter'||key==='priceDry')update('price',event.target.value)}}/></div></Field>;
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="modal dish-editor-modal" role="dialog" aria-modal="true" aria-label={item?'Edit dish':'Add dish'}>
    <div className="modal-head"><div><h2>{item?'Edit Food Item':'Add Food Item'}</h2><p>Upload a dish photo, set pricing, dietary flags, and nutritional details.</p></div><button className="button secondary" onClick={close}>Cancel</button></div>
    <div className="dish-editor-grid"><div className="dish-editor-main">
      <section className="dish-form-section"><div className="dish-section-heading"><span><UtensilsCrossed size={16}/></span><div><strong>Dish Information</strong><small>Primary details shown to diners on your digital menu.</small></div></div>
        <div className="dish-form-two"><Field label="Dish name *"><input autoFocus required value={form.name||''} placeholder="e.g. Hyderabadi Dum Biryani" onChange={event=>update('name',event.target.value)}/></Field><Field label="Category *"><select required value={form.category||''} onChange={event=>update('category',event.target.value)}><option value="">Select category…</option>{[...new Set([...categories,item?.category||''])].filter(Boolean).map(category=><option key={category}>{category}</option>)}</select></Field></div>
        <div className="dish-subheading">PRICING STRUCTURE <b>*</b></div><div className="pricing-mode-tabs">{[['SINGLE','Single Fixed Price'],['PORTIONS','Portions (¼, ½, Full)'],['DRY_GRAVY','Dry & Gravy Prices']].map(([value,label])=><button type="button" key={value} className={(form.pricingMode||'SINGLE')===value?'selected':''} onClick={()=>update('pricingMode',value)}>{label}</button>)}</div>
        {(!form.pricingMode||form.pricingMode==='SINGLE')?priceField('price','Price (INR) *'):form.pricingMode==='PORTIONS'?<div className="dish-form-three">{priceField('priceQuarter','¼ Portion (INR)')}{priceField('priceHalf','½ Portion (INR)')}{priceField('priceFull','Full Portion (INR)')}</div>:<div className="dish-form-two">{priceField('priceDry','Dry (INR)')}{priceField('priceGravy','Gravy (INR)')}</div>}
        <div className="dish-subheading">DIETARY CLASSIFICATION <b>*</b></div><div className="diet-choice">{[['Veg','Vegetarian','🌿'],['Non-Veg','Non-Vegetarian','🍗']].map(([value,label,emoji])=><button type="button" key={value} className={`${value==='Veg'?'vegetarian':'nonvegetarian'} ${(form.type||item?.type||'Veg')===value?'selected':''}`} onClick={()=>update('type',value)}><i/>{label} <span>{emoji}</span></button>)}</div>
        <Field label="Dish description"><textarea rows={3} value={form.description||''} placeholder="Describe flavours, preparation style, or signature ingredients…" onChange={event=>update('description',event.target.value)}/></Field>
      </section>
      <label className="dish-stock-setting"><span><strong>Live Stock Availability</strong><small>Dish is available and can be ordered by diners.</small></span><input type="checkbox" checked={(form.available||'Available')!=='Unavailable'} onChange={event=>update('available',event.target.checked?'Available':'Unavailable')}/></label>
      <section className="dish-form-section nutrition-section"><button className="nutrition-toggle" type="button" onClick={()=>setNutritionOpen(value=>!value)}><span><ImagePlus size={16}/></span><span><strong>Culinary Details & Nutrition</strong><small>Spice level, dietary tags, allergens, and prep time</small></span><ChevronDown size={16}/></button>{nutritionOpen&&<div className="nutrition-content"><div className="dish-form-three"><Field label="Preparation time"><select value={form.time||'15 min'} onChange={event=>update('time',event.target.value)}>{['5 min','10 min','15 min','20 min','30+ min'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Spice level"><select value={form.spice||'Medium'} onChange={event=>update('spice',event.target.value)}>{['Not spicy','Mild','Medium','Spicy','Very spicy'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Serving size"><select value={form.serving||'Serves 1'} onChange={event=>update('serving',event.target.value)}>{['Serves 1','Serves 2','Family','Small','Medium','Large'].map(value=><option key={value}>{value}</option>)}</select></Field></div><Field label="Ingredients (comma separated)"><input value={form.ingredients||''} placeholder="Chicken, rice, spices" onChange={event=>update('ingredients',event.target.value)}/></Field><Field label="Allergens (comma separated)"><input value={form.allergens||''} placeholder="Milk, nuts, gluten" onChange={event=>update('allergens',event.target.value)}/></Field><div className="dish-subheading">NUTRITION PER SERVING</div><div className="dish-form-four">{[['calories','Calories (kcal)'],['protein','Protein (g)'],['carbs','Carbs (g)'],['fat','Fat (g)']].map(([key,label])=><Field key={key} label={label}><input type="number" min="0" value={form[key]||''} onChange={event=>update(key,event.target.value)}/></Field>)}</div></div>}</section>
    </div><aside className="dish-editor-side"><section className="dish-form-section dish-photo-section"><div className="dish-section-heading"><div><strong>Dish Photo</strong><small>Square images look best on the guest menu.</small></div><span className="photo-recommended">PRIMARY PHOTO</span></div><div className="dish-upload-preview">{selectedImage.startsWith('data:')||selectedImage.startsWith('http')||selectedImage.startsWith('/uploads/')?<img src={selectedImage} alt="Dish preview"/>:<div className="dish-upload-placeholder"><Camera size={24}/><strong>Add front view photo</strong><small>Take a clear photo of the plated dish.</small></div>}</div><div className="dish-upload-buttons"><label className="button primary"><Camera size={15}/> Camera<input type="file" accept="image/*" capture="environment" onChange={event=>readImage(event.target.files?.[0])}/></label><label className="button secondary"><Upload size={15}/> Browse<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>readImage(event.target.files?.[0])}/></label></div><small className="upload-help">Supports JPG, PNG, WebP · Max 5 MB</small></section>
      <section className="dish-form-section live-preview"><div className="dish-section-heading"><div><strong>Live Customer Preview</strong><small>Here is how diners will see this dish.</small></div><span className="photo-recommended">REAL-TIME</span></div><article className="dish-preview-card"><div className="dish-preview-image">{selectedImage.startsWith('data:')||selectedImage.startsWith('http')||selectedImage.startsWith('/uploads/')?<img src={selectedImage} alt="Dish"/>:<UtensilsCrossed size={20}/>}</div><div className="dish-preview-copy"><span className={(form.type||'Veg')==='Veg'?'veg':'nonveg'}>▣ {(form.type||'Veg')==='Veg'?'Veg':'Non-Veg'}</span><h3>{form.name||'Dish Name'}</h3><p>{form.description||'A flavorful creation made fresh with signature ingredients.'}</p><strong>₹{previewPrice||'0.00'}</strong></div></article>
    </section></aside></div><div className="dish-modal-actions"><button className="button secondary" onClick={close}>Cancel</button><button className="button primary" onClick={save}><Check size={16}/>{item?'Save Changes':'Save Food Item'}</button></div>
  </section></div>;
}
