'use client';
import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, RotateCcw, Search, ShoppingBag, Timer, Wallet } from 'lucide-react';

type OrderRow = { dbId: string; id: string; restaurant: string; table: string; items: string; customer: string; amount: number; status: string; time: string };
type ApiOrder = { id: string; displayId: string; restaurant: { name: string }; table: { label: string } | null; items: { quantity: number }[]; customerName: string | null; total: number | string; status: string; createdAt: string };
const statuses=['New','Confirmed','Preparing','Ready','Served','Cancelled'];
export function OrdersPage({search,setSearch,notice}:{search:string;setSearch:(v:string)=>void;notice:(s:string)=>void}) {
 const [orders,setOrders]=useState<OrderRow[]>([]); const [filter,setFilter]=useState('All orders'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/orders?pageSize=100');if(!response.ok)throw new Error('request failed');const result=await response.json() as {data:ApiOrder[]};setOrders(result.data.map(o=>({dbId:o.id,id:o.displayId,restaurant:o.restaurant.name,table:o.table?.label||'—',items:`${o.items.reduce((sum,x)=>sum+x.quantity,0)} items`,customer:o.customerName||'Guest',amount:Number(o.total),status:o.status[0]+o.status.slice(1).toLowerCase(),time:new Date(o.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})})));}catch{setError('Unable to load orders. Please try again.');}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 const rows=orders.filter(o=>(filter==='All orders'||o.status===filter)&&(!search||`${o.id} ${o.restaurant} ${o.table} ${o.customer}`.toLowerCase().includes(search.toLowerCase())));
 async function setStatus(order:OrderRow,status:string){const previous=order.status;setOrders(current=>current.map(item=>item.id===order.id?{...item,status}:item));const response=await fetch('/api/orders',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:order.dbId,status:status.toUpperCase()})});if(!response.ok){setOrders(current=>current.map(item=>item.id===order.id?{...item,status:previous}:item));notice('Could not update order status');return}notice(`${order.id} marked ${status.toLowerCase()}`);}
 return <><div className="page-heading"><div><div className="eyebrow">THE HEART OF SERVICE</div><h1>Orders</h1><p>Keep every order moving smoothly, from the first scan to the last bite.</p></div><button className="button secondary" onClick={()=>void refresh().then(()=>{if(!error)notice('Orders refreshed')})} disabled={loading}><RotateCcw size={16}/>Refresh</button></div>
 <div className="order-metrics"><div><span className="metric-icon teal"><ShoppingBag size={18}/></span><strong>{orders.length}</strong><small>Orders loaded</small></div><div><span className="metric-icon orange"><Clock3 size={18}/></span><strong>{orders.filter(o=>['New','Confirmed','Preparing'].includes(o.status)).length}</strong><small>Need attention</small></div><div><span className="metric-icon green"><Wallet size={18}/></span><strong>₹{orders.reduce((a,o)=>a+o.amount,0).toLocaleString('en-IN')}</strong><small>Order value</small></div><div><span className="metric-icon blue"><Timer size={18}/></span><strong>Live</strong><small>Operational orders</small></div></div>
 <section className="panel list-panel"><div className="panel-heading-inline"><div><h2>Recent orders</h2><p>A little attention makes every guest feel looked after.</p></div><span className="live-pill"><i/>Updates in real time</span></div><div className="toolbar"><div className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, restaurant or table..."/></div><select className="toolbar-select" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter orders by status">{['All orders',...statuses].map(s=><option key={s}>{s}</option>)}</select><button className="filter-button" disabled title="Date filter is not available yet"><CalendarDays size={15}/>Today</button></div>
 {error?<div className="empty-state"><h3>Orders could not be loaded</h3><p>{error}</p><button className="button secondary" onClick={()=>void refresh()}>Try again</button></div>:loading?<div className="empty-state" role="status">Loading orders…</div>:rows.length===0?<div className="empty-state"><div><ShoppingBag size={22}/></div><h3>{orders.length?'No matching orders':'No orders yet'}</h3><p>{orders.length?'Try a different search or status filter.':'Orders will appear here when guests place them.'}</p></div>:<div className="table-scroll"><table className="data-table"><thead><tr><th>ORDER</th><th>RESTAURANT</th><th>TABLE</th><th>ITEMS</th><th>CUSTOMER</th><th>AMOUNT</th><th>STATUS</th><th>TIME</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><strong className="order-id">{o.id}</strong></td><td>{o.restaurant}</td><td>{o.table}</td><td>{o.items}</td><td>{o.customer}</td><td><strong>₹{o.amount}</strong></td><td><select aria-label={`Status for ${o.id}`} className={`status-select status-${o.status.toLowerCase()}`} value={o.status} onChange={e=>void setStatus(o,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td>{o.time}</td></tr>)}</tbody></table></div>}
 <div className="table-foot"><span>Showing <b>{rows.length}</b> orders</span><div className="pagination"><button disabled><ChevronLeft size={14}/>Previous</button><button className="page-current">1</button><button disabled>Next<ChevronRight size={14}/></button></div></div></section></>;
}
