'use client';
import { useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, Download, ShieldCheck } from 'lucide-react';
type RestaurantOption={id?:string;name:string};
type ReportPayload={type:string;range:string;from:string;to:string;data:Array<Record<string,string|number|boolean|null>>;metrics:{rows:number;revenue:number;averageRating:number;scans:number}};
const reportTypes=['Restaurant performance','QR scan report','Order report','Menu report','Review report','User activity'];
const dateFilteredReports=['Menu report','Order report','Review report','User activity'];
function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function localDay(date:string,end=false){const [year,month,day]=date.split('-').map(Number);return new Date(year,month-1,day,end?23:0,end?59:0,end?59:0,end?999:0)}
function reportBounds(range:string,from:string,to:string){const now=new Date();const start=new Date(now);start.setHours(0,0,0,0);if(range==='Last 7 days')start.setDate(start.getDate()-6);else if(range==='Last 30 days')start.setDate(start.getDate()-29);else if(range==='This month')start.setDate(1);else if(range==='Custom range')return {from:localDay(from).toISOString(),to:localDay(to,true).toISOString()};return {from:start.toISOString(),to:now.toISOString()}}
function dateKey(value:string){const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function reportDateLabel(report:ReportPayload){return dateFilteredReports.includes(report.type)?`${new Date(report.from).toLocaleDateString()} to ${new Date(report.to).toLocaleDateString()}`:'All time'}
function ReportButton({children,onClick,disabled=false,kind='primary',icon}:{children:ReactNode;onClick:()=>void;disabled?:boolean;kind?:'primary'|'secondary';icon?:ReactNode}){return <button className={`button ${kind}`} disabled={disabled} onClick={onClick}>{icon}{children}</button>}
function toCsv(report:ReportPayload){const headers=Object.keys(report.data[0]||{Message:'No records for selected filters'});const rows=report.data.length?report.data:[{Message:'No records for selected filters'}];return [headers,...rows.map(row=>headers.map(key=>row[key]??''))].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n');}
export function ReportsPage({restaurants,notice}:{restaurants:RestaurantOption[];notice:(message:string)=>void}){
 const [kind,setKind]=useState(reportTypes[0]),[range,setRange]=useState('Last 7 days'),[restaurant,setRestaurant]=useState('All restaurants'),[customFrom,setCustomFrom]=useState(''),[customTo,setCustomTo]=useState(''),[report,setReport]=useState<ReportPayload|null>(null),[busy,setBusy]=useState('');
 const selected=restaurants.find(x=>x.name===restaurant);
 const dateFilterAvailable=dateFilteredReports.includes(kind);
 async function generate(){if(dateFilterAvailable&&range==='Custom range'&&(!customFrom||!customTo||customFrom>customTo)){notice('Choose a valid start and end date');return}setBusy('report');setReport(null);try{const bounds=dateFilterAvailable?reportBounds(range,customFrom,customTo):null;const query=new URLSearchParams({type:kind,range,...(bounds||{}),...(selected?.id?{restaurantId:selected.id}:{})});const response=await fetch(`/api/reports?${query}`);const body=await response.json();if(!response.ok)throw new Error(body.error);setReport(body as ReportPayload);notice('Report data refreshed')}catch{notice('Unable to load this report. Please try again.')}finally{setBusy('')}}
 async function exportFile(format:'csv'|'xlsx'|'pdf'){
  if(!report){notice('Generate the report before exporting');return}setBusy(format);
  try{
   const filename=`scanzaa-${kind.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${dateFilteredReports.includes(report.type)?`${dateKey(report.from)}-to-${dateKey(report.to)}`:'all-time'}`;
   if(format==='csv')downloadBlob(new Blob(['\ufeff',toCsv(report)],{type:'text/csv;charset=utf-8'}),`${filename}.csv`);
   if(format==='xlsx'){
    const ExcelJS=(await import('exceljs')).default;const workbook=new ExcelJS.Workbook();workbook.creator='Scanzaa';workbook.created=new Date();workbook.subject=`${kind} · ${reportDateLabel(report)}`;const sheet=workbook.addWorksheet(kind.slice(0,31));
    const headers=Object.keys(report.data[0]||{Message:'No records for selected filters'});sheet.columns=headers.map(key=>({header:key.replaceAll('_',' '),key,width:Math.min(36,Math.max(14,key.length+3))}));
    for(const row of report.data)sheet.addRow(Object.fromEntries(headers.map(key=>[key,key.endsWith('_At')&&row[key]?new Date(String(row[key])):row[key]])));
    sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF176D61'}};sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:headers.length}};
    const buffer=await workbook.xlsx.writeBuffer();downloadBlob(new Blob([new Uint8Array(buffer)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`${filename}.xlsx`);
   }
   if(format==='pdf'){
    const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const doc=new jsPDF({orientation:'landscape',unit:'pt',format:'a4'});const columns=Object.keys(report.data[0]||{Message:'No records for selected filters'});const rows=report.data.length?report.data.map(row=>columns.map(key=>String(row[key]??''))):[['No records for selected filters']];
    doc.setFillColor(23,109,97);doc.rect(0,0,doc.internal.pageSize.getWidth(),82,'F');doc.setTextColor(255,255,255);doc.setFontSize(11);doc.text('SCANZAA · POWERED BY RENZA',36,27);doc.setFontSize(21);doc.text(kind,36,57);doc.setTextColor(50,62,57);doc.setFontSize(10);doc.text(`${restaurant} · ${reportDateLabel(report)} · Generated ${new Date().toLocaleDateString()}`,36,105);doc.text(`Rows: ${report.metrics.rows}   Scans: ${report.metrics.scans}   Order value: INR ${report.metrics.revenue.toLocaleString('en-IN')}   Avg rating: ${report.metrics.averageRating.toFixed(2)}`,36,124);
    autoTable(doc,{startY:145,head:[columns.map(key=>key.replaceAll('_',' '))],body:rows,styles:{fontSize:8,cellPadding:5,overflow:'linebreak'},headStyles:{fillColor:[23,109,97]},alternateRowStyles:{fillColor:[244,248,246]},margin:{left:36,right:36}});doc.save(`${filename}.pdf`);
   }
   notice(`${format.toUpperCase()} report downloaded`);
  }catch{notice(`Unable to generate the ${format.toUpperCase()} report. Please try again.`)}finally{setBusy('')}
 }
 const cards=[['Restaurant performance','Partner activity, restaurant status, tables and menu counts.','◈'],['QR scan report','Scan counts and active QR status by restaurant table.','⌗'],['Order report','Order volumes and revenue by location.','↗'],['Menu report','Menu items, prices and availability.','▤'],['Review report','Guest ratings and comments.','☆'],['User activity','Auditable changes across the workspace.','◷']];
 return <><div className="page-heading"><div><div className="eyebrow">INSIGHT, MADE PRACTICAL</div><h1>Reports & exports</h1><p>Build a filtered report and export the same data as CSV, Excel or PDF.</p></div><ReportButton kind="secondary" disabled onClick={()=>{}} icon={<CalendarDays size={16}/>}>Scheduling unavailable</ReportButton></div>
 <section className="report-builder panel"><div className="report-builder-head"><div className="report-builder-icon"><BarChart3 size={19}/></div><div><h2>Build a report</h2><p>Choose the data and filters for this report.</p></div></div><div className="report-controls"><label className="field"><span>Report type</span><select aria-label="Report type" value={kind} onChange={e=>{const next=e.target.value;setKind(next);if(!dateFilteredReports.includes(next)&&range==='Custom range')setRange('Last 7 days');setReport(null)}}>{reportTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Date range</span><select aria-label="Date range" value={range} disabled={!dateFilterAvailable} onChange={e=>{setRange(e.target.value);setReport(null)}}>{['Today','Last 7 days','Last 30 days','This month','Custom range'].map(x=><option key={x}>{x}</option>)}</select><small>{dateFilterAvailable?'Applied to report data':'Current/lifetime totals; date filtering is not available for this report type.'}</small></label><label className="field"><span>Restaurant</span><select aria-label="Restaurant" value={restaurant} onChange={e=>{setRestaurant(e.target.value);setReport(null)}}><option>All restaurants</option>{restaurants.map(x=><option key={x.id||x.name}>{x.name}</option>)}</select></label><ReportButton disabled={busy==='report'||(dateFilterAvailable&&range==='Custom range'&&(!customFrom||!customTo||customFrom>customTo))} onClick={()=>void generate()} icon={<BarChart3 size={16}/>}>{busy==='report'?'Generating…':'Generate report'}</ReportButton></div>{range==='Custom range'&&dateFilterAvailable&&<div className="form-grid custom-date-fields"><label className="field"><span>From</span><input aria-label="From date" type="date" value={customFrom} onChange={e=>{setCustomFrom(e.target.value);setReport(null)}}/></label><label className="field"><span>To</span><input aria-label="To date" type="date" value={customTo} onChange={e=>{setCustomTo(e.target.value);setReport(null)}}/></label></div>}
 {report&&<><div className="report-preview"><div><div className="report-preview-kicker">FILTERED REPORT</div><h3>{report.type}</h3><p>{restaurant} <span>·</span> {reportDateLabel(report)} <span>·</span> {report.metrics.rows} rows</p></div><div className="report-preview-stat"><strong>{report.metrics.rows.toLocaleString()}</strong><small>records</small></div><div className="report-preview-stat"><strong>{report.metrics.scans.toLocaleString()}</strong><small>QR scans</small></div><div className="report-preview-stat"><strong>₹{report.metrics.revenue.toLocaleString('en-IN')}</strong><small>order value</small></div></div><div className="table-scroll"><table className="data-table"><thead><tr>{Object.keys(report.data[0]||{Message:'Report'}).map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{report.data.slice(0,20).map((row,i)=><tr key={i}>{Object.values(row).map((v,j)=><td key={j}>{v===null?'':String(v)}</td>)}</tr>)}</tbody></table>{report.data.length===0&&<div className="empty-state"><h3>No matching data</h3><p>Try another report type, restaurant, or period.</p></div>}</div></>}
 <div className="report-export-row"><span><ShieldCheck size={15}/> Exports use the generated report filters and rows.</span><div>{(['csv','xlsx','pdf'] as const).map(format=><button key={format} className="button secondary" disabled={!report||report.data.length===0||Boolean(busy)} onClick={()=>void exportFile(format)}><Download size={15}/>{busy===format?`Generating ${format.toUpperCase()}…`:format.toUpperCase()}</button>)}</div></div></section>
 <div className="section-label-row report-library-title"><div><h2>Explore report types</h2><p>Select a report to use the same filters and export flow.</p></div></div><div className="report-card-grid">{cards.map(([name,desc,icon])=><button key={name} className={`report-card ${kind===name?'report-selected':''}`} onClick={()=>{setKind(name);if(!dateFilteredReports.includes(name)&&range==='Custom range')setRange('Last 7 days');setReport(null)}}><span className="report-card-icon">{icon}</span><strong>{name}</strong><p>{desc}</p><span className="report-card-link">Use this report <ArrowRight size={14}/></span></button>)}</div></>;
}
