import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@/lib/db'; import { requireUser } from '@/lib/auth'; import { jsonError, pageArgs } from '@/lib/http';
const schema = z.object({ name: z.string().trim().min(2).max(120), externalId: z.string().optional(), description: z.string().optional(), cuisine: z.array(z.string()).default([]), phone: z.string().optional(), email: z.string().email().optional().or(z.literal('')), website: z.string().optional(), address: z.string().optional(), city: z.string().optional(), state: z.string().optional(), country: z.string().default('India'), pincode: z.string().optional(), openingTime: z.string().optional(), closingTime: z.string().optional(), workingDays: z.array(z.string()).default([]), logoUrl: z.string().optional() });
export async function GET(req: NextRequest) {
  try { await requireUser('restaurants.read'); const { page, pageSize, skip } = pageArgs(req.url); const q = req.nextUrl.searchParams.get('search') || ''; const status = req.nextUrl.searchParams.get('status'); const where = { deletedAt: null, ...(q ? { OR: [{ name: { contains: q, mode: 'insensitive' as const } }, { city: { contains: q, mode: 'insensitive' as const } }, { email: { contains: q, mode: 'insensitive' as const } }] } : {}), ...(status ? { status: status as 'ACTIVE' | 'SUSPENDED' | 'ONBOARDING' } : {}) }; const [data, total] = await Promise.all([db.restaurant.findMany({ where, skip, take: pageSize, orderBy: { createdAt: 'desc' }, include:{_count:{select:{tables:true}}} }), db.restaurant.count({ where })]); return NextResponse.json({ data, page, pageSize, total, pages: Math.ceil(total / pageSize) }); } catch (e) { return jsonError(e); }
}
export async function POST(req: NextRequest) {
  try { const user = await requireUser('restaurants.write'); const input = schema.parse(await req.json()); const slug = `${input.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${crypto.randomUUID().slice(0, 6)}`; const restaurant = await db.restaurant.create({ data: { ...input, email: input.email || null, slug } }); await db.auditLog.create({ data: { actorId: user.id, restaurantId: restaurant.id, action: 'restaurant.created', objectType: 'Restaurant', objectId: restaurant.id } }); return NextResponse.json(restaurant, { status: 201 }); } catch (e) { return jsonError(e); }
}
