'use client';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
type Item = { id: string; name: string; description: string; imageUrl: string; price: string | number; categoryId: string | null; available: boolean };
type Menu = { restaurant: { name: string; description: string | null; logoUrl: string | null }; table: { label: string }; categories: { id: string; name: string }[]; items: Item[] };
export default function PublicMenuPage() {
 const { token } = useParams<{ token: string }>(); const [menu,setMenu]=useState<Menu|null>(null); const [error,setError]=useState(''); const [cart,setCart]=useState<Record<string,number>>({}); const [customerName,setCustomerName]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 useEffect(()=>{fetch(`/api/public/menu/${token}`).then(async r=>{if(!r.ok)throw new Error('This menu is currently unavailable.');return r.json()}).then(setMenu).catch(e=>setError(e.message));},[token]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0); const total=useMemo(()=>menu?.items.reduce((sum,item)=>sum+(cart[item.id]||0)*Number(item.price),0)||0,[menu,cart]);
 async function placeOrder(){if(!menu||!count)return;setBusy(true);try{const response=await fetch('/api/public/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,customerName:customerName||undefined,items:Object.entries(cart).filter(([,quantity])=>quantity>0).map(([menuItemId,quantity])=>({menuItemId,quantity}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not place order');setCart({});setNotice(`Order ${data.displayId} placed. Thank you!`);}catch(e){setNotice(e instanceof Error?e.message:'Could not place order');}finally{setBusy(false);}}
 if(error)return <main className="customer-menu"><section className="customer-card"><b>SCANZAA</b><h1>Menu unavailable</h1><p>{error}</p></section></main>;
 if(!menu)return <main className="customer-menu"><section className="customer-card"><b>SCANZAA</b><p>Loading menu…</p></section></main>;
 return <main className="customer-menu"><header className="customer-header">{menu.restaurant.logoUrl&&<img src={menu.restaurant.logoUrl} alt=""/>}<div><b>SCANZAA</b><h1>{menu.restaurant.name}</h1><p>{menu.table.label} · {menu.restaurant.description}</p></div></header><section className="customer-menu-items">{menu.categories.map(category=><div key={category.id}><h2>{category.name}</h2>{menu.items.filter(item=>item.categoryId===category.id).map(item=><article className="customer-menu-item" key={item.id}>{item.imageUrl&&<img src={item.imageUrl} alt=""/>}<div><h3>{item.name}</h3><p>{item.description}</p><strong>₹{Number(item.price).toFixed(2)}</strong></div><div className="customer-qty"><button aria-label={`Remove one ${item.name}`} onClick={()=>setCart(c=>({...c,[item.id]:Math.max(0,(c[item.id]||0)-1)}))}>−</button><span>{cart[item.id]||0}</span><button aria-label={`Add one ${item.name}`} onClick={()=>setCart(c=>({...c,[item.id]:(c[item.id]||0)+1}))}>+</button></div></article>)}</div>)}{menu.items.filter(item=>!item.categoryId).map(item=><article className="customer-menu-item" key={item.id}><div><h3>{item.name}</h3><p>{item.description}</p><strong>₹{Number(item.price).toFixed(2)}</strong></div><button onClick={()=>setCart(c=>({...c,[item.id]:(c[item.id]||0)+1}))}>Add</button></article>)}</section>{count>0&&<section className="customer-checkout"><label>Your name (optional)<input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Name for your order"/></label><button disabled={busy} onClick={placeOrder}>{busy?'Placing order…':`Place order · ₹${total.toFixed(2)}`}</button>{notice&&<p>{notice}</p>}</section>}</main>;
}
